# Generated by Django 5.1.2 on 2025-05-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("open_date", models.DateTimeField()),
                ("expire_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Open", "Open"),
                            ("Under Evaluation", "Under Evaluation"),
                            ("Closed", "Closed"),
                            ("Awarded", "Awarded"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TenderCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Open", "Open"),
                            ("Under Evaluation", "Under Evaluation"),
                            ("Closed", "Closed"),
                            ("Awarded", "Awarded"),
                        ],
                        default="EVAULATION",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenders.tender",
                    ),
                ),
            ],
        ),
    ]
