# Generated by Django 5.1.2 on 2025-05-03 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("open_date", models.DateTimeField()),
                ("expire_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Open", "Open"),
                            ("Under Evaluation", "Under Evaluation"),
                            ("Closed", "Closed"),
                            ("Awarded", "Awarded"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentTender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="tender_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenders.tender",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenderCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Evaluation", "Evaluation"),
                            ("Application", "Application"),
                            ("Qualification", "Qualification"),
                        ],
                        default="Evaluation",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("document", "document"),
                            ("description", "description"),
                        ],
                        default="description",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("weight", models.FloatField(default=0.0)),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="tenders.tender",
                    ),
                ),
            ],
        ),
    ]
