# Generated by Django 5.1.2 on 2025-05-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tendercriteria",
            name="category",
            field=models.CharField(
                choices=[
                    ("Evaluation", "Evaluation"),
                    ("Application", "Application"),
                    ("Qualification", "Qualification"),
                ],
                default="Evaluation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tendercriteria",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="tenders.tender",
            ),
        ),
    ]
