# Generated by Django 5.1.2 on 2025-05-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0002_alter_tendercriteria_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTenderCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="criteria_document")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tender_criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenders.tendercriteria",
                    ),
                ),
            ],
        ),
    ]
