# Generated by Django 5.1.2 on 2025-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0003_documenttendercriteria"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documenttendercriteria",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="documenttendercriteria",
            name="document",
            field=models.FileField(upload_to="criteria_documents/"),
        ),
    ]
