# Generated by Django 5.1.2 on 2025-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenders",
            "0004_rename_created_at_documenttendercriteria_uploaded_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tendercriteria",
            old_name="content",
            new_name="description",
        ),
        migrations.AddField(
            model_name="tendercriteria",
            name="weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="tender",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
