# Generated by Django 5.1.2 on 2025-05-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0005_rename_content_tendercriteria_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tendercriteria",
            name="type",
            field=models.CharField(
                choices=[("document", "document"), ("description", "description")],
                default="description",
                max_length=20,
            ),
        ),
    ]
