# Generated by Django 5.1.2 on 2025-05-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="criteriacompleted",
            old_name="tender",
            new_name="application",
        ),
    ]
